
use etsy_sales;
DROP TABLE tempOrders;
create TABLE tempOrders (
  SaleDate VARCHAR(8) NOT NULL,
  OrderId INT UNSIGNED NOT NULL,
  PRIMARY KEY (OrderId),
  BuyerUserId VARCHAR(100),
  FullName VARCHAR(50),
  FirstName VARCHAR(50),
  LastName VARCHAR(50),
  NumberOfItems INT UNSIGNED,
  PaymentMethod VARCHAR(20),
  DateShipped VARCHAR(8),
  Street1 VARCHAR(50),
  Street2 VARCHAR(50),
  ShipCity VARCHAR(50),
  ShipState VARCHAR(50),
  ShipZipCode VARCHAR(20),
  ShipCountry VARCHAR(20),
  Currency VARCHAR(10),
  OrderValue DECIMAL(6,2) DEFAULT 0.0,
  CouponCode VARCHAR(20),
  CouponDetails VARCHAR(20),
  DiscountAmount DECIMAL(6,2) DEFAULT 0.0,
  ShippingDiscount DECIMAL(6,2) DEFAULT 0.0,
  Shipping DECIMAL(6,2) DEFAULT 0.0,
  SalesTax DECIMAL(6,2) DEFAULT 0.0,
  OrderTotal DECIMAL(6,2) DEFAULT 0.0,
  Status VARCHAR(20),
  CardProcessingFees DECIMAL(6,2) DEFAULT 0.0,
  OrderNet DECIMAL(6,2) DEFAULT 0.0,
  AdjustedOrderTotal DECIMAL(6,2) DEFAULT 0.00 NULL,
  AdjustedCardProcessingFees DECIMAL(6,2) DEFAULT 0.0,
  AdjustedNetOrderAmount DECIMAL(6,2) DEFAULT 0.0,
  Buyer VARCHAR(50),
  OrderType VARCHAR(50),
  PaymentType VARCHAR(50),
  InPersonDiscount DECIMAL(6,2) DEFAULT 0.0,
  InPersonLocation VARCHAR(50)
)
